### ISSUE TITLE
Source path does not exist: img/icons/icon.png

### ISSUE THREAD

**Issue by JesusDiazDiaz** [fraigo/vuetify-cordova#1]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuetify-cordova@1.0.0 cordova-build: `npm run build && cordova build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vuetify-cordova@1.0.0 cordova-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by manojpj** [comment]
Got any solution ? @JesusDiazDiaz

**Comment by fraigo** [comment]
Code is updated, fixed config.xml icon references.
